# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NihonGoFlip
email: zheisey@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  NihonGoFlip is a fun, visually interactive way to learn Hiragana and
  Katakana on the web. Best of all, it's totlly free!
baseurl: "/NihonGoFlip" # the subpath of your site, e.g. /blog
url: "http://zac-heisey.github.io" # the base hostname & protocol for your site
twitter_username: zac_heisey
github_username:  zac-heisey

# Build settings
markdown: kramdown
