# Site settings
title = "NihonGoFlip | Learn Hiragana & Katakana Online"
baseURL = "" # Hostname (and path) to the root, e.g. http://bep.is/
languageCode = "en-us"

[params]
  email = "zheisey@gmail.com"
  description = "NihonGoFlip is a fun, visually interactive way to learn Hiragana and Katakana on the web. Best of all, it's totally free!"
  twitter_username = "zac_heisey"
  github_username = "zac-heisey"
